### ISSUE TITLE
Attempting to run pdfimages throws VCruntime dependency error

### ISSUE THREAD

**Issue by GitHubRulesOK** [cpp-tutor/xpdf-tiff-patches#1]
Understandable but undesirable 
```
---------------------------
pdfimages.exe - System Error
---------------------------
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```
For a windows 11 novice there is no explanation that the runtime redist is obtainable  cleanly from Microsoft https://www.microsoft.com/en-us/download/details.aspx?id=52685 rather than some "fix my PC" cowboys.

![image](https://user-images.githubusercontent.com/12754913/163372666-c6804e09-213d-4cb7-8602-4ea63d6cdbcd.png)

**Comment by cpp-tutor** [comment]
Okay, so I did a google for "VCRUNTIME140.dll" and I agree some of the links didn't look good. Note that while I'm pleased the 2015 C++ Redistributable worked for you, all of the .exe files in the Release archive were compiled with Visual Studio 2017 C++ (as mentioned in the blog article linked from the README.md).

Further research finds: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

Quoting from this page: "any apps built by the Visual Studio 2015, 2017, 2019, or 2022 toolsets can use the latest Microsoft Visual C++ Redistributable"

If you could confirm that the correct redist linked from the above page allows the .exe to run (the executables themselves are 32-bit, I assume you are using 64-bit Windows 11?) I will add a note to both the README.md and the blog article containing the above link.

**Comment by GitHubRulesOK** [comment]
Ok from the link I first took and ran 32 bit variant (yes its a 64 bit sandbox but had assumed need for 32bit runtime)
![image](https://user-images.githubusercontent.com/12754913/163568735-990211ab-0699-4f88-97b5-7f0ce5e7a359.png)

then since available running `SandBox\pdfimages-4.03-20211110\pdfimages.exe` works so expect reverse order should too
```
pdfimages version 4.03 [www.xpdfreader.com]
Copyright 1996-2021 Glyph & Cog, LLC
Usage: pdfimages [options] <PDF-file> <image-root>
  -f <int>       : first page to convert
  -l <int>       : last page to convert
  -j             : write JPEG images as JPEG files
  -raw           : write raw data in PDF-native formats
  -png           : write images as PNG files (can combine with -j)
  -tiff          : write images as TIFF files (can combine with -j)
  -list          : write information to stdout for each image
  -opw <string>  : owner password (for encrypted files)
  -upw <string>  : user password (for encrypted files)
  -q             : don't print any messages or errors
  -cfg <string>  : configuration file to use in place of .xpdfrc
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information
```
sidenote Are these enhancements automatically ported into next xpdf version 4.04 ?

**Comment by cpp-tutor** [comment]
> Are these enhancements automatically ported into next xpdf version 4.04 ?

I don't think the xpdf author wants to merge these patches unfortunately, so I'll have to continue to make a new set of patches and binaries whenever a new version is released. (That is the reason for this repo existing!)

> `Syntax Warning: Annotation destination array is too short`

I have no idea what this indicates, this must be an xpdf library error rather than a bug in `pdfimages.exe`. You could try the following:

1. Grab the images page by page, using options `-f 1 -l 1 -list` for the first page, and so on. This may highlight which page(s) show(s) the problem.
2. Ask for help on the xpdf forum (this is quite active and is a direct route to the xpdf author): http://forum.xpdfreader.com/
3. Run the source PDF through GhostScript (the `ps2pdf` utility) to try to "clean" it (or convert it to another, possibly lower, PDF spec) then run `pdfimages.exe` on the result.

**Comment by GitHubRulesOK** [comment]
Thanks
For what its worth  `-f 1 -l 1 -list` still throws the whole file 12 X warnings !! its a 800+ page Microsoft self generated help document so they should have checked :-) but its oddly built using wkhtmltopdf dev, QT4 version, and possibly massaged by iTextSharp 5 `wow, plagiarism or what !` anyway it is clean looking for images but I do get odd output in the properties so perhaps it is poorly built meta data

**Comment by cpp-tutor** [comment]
No problem. You could try the "plain" xpdf 4.03 `pdfimages.exe` and see if you get the same warnings (you probably will, I'd imagine) and even try `pdftohtml.exe` from the same archive? Not sure what you're trying to achieve but this should extract the images and annotations too, plus all the hyperlinks etc. (to .html/.png/.jpg).
