### ISSUE TITLE
Highlight Default Settings

### ISSUE THREAD

**Issue by flywire** [cpp-tutor/xpdf-tiff-patches#2]
It would be nice if default settings were clearer in the help. Something like first option in all caps or enclose in brackets.

**Comment by cpp-tutor** [comment]
Do you mean the output from running **pdftotiff.exe -?**? The defaults are applied in the absence of the user specifying any options, for example 24bit RGB, no alpha channel, 150 DPI, LZW compression.

I'm afraid I'm still unsure of exactly what is meant by "first option"; the option descriptions are based on those for the other tools, in particular **pdftopng**.

**Comment by flywire** [comment]
Yes, I just mean explicitly state defaults in the help (like default dpi).

The defaults aren't clear:
```
pdftotiff version 4.04
Copyright 1996-2022 Glyph & Cog, LLC
Usage: pdftotiff [options] <PDF-file> <TIFF-root>
  -f <int>                : first page to print
  -l <int>                : last page to print
  -r <number>             : resolution, in DPI (default is 150)
  -mono                   : generate a monochrome TIFF file
  -gray                   : generate a grayscale TIFF file
  -cmyk                   : generate a CMYK TIFF file
  -no-compression         : disable TIFF compression
  -alpha                  : include an alpha channel in the TIFF file
  -freetype <string>      : enable FreeType font rasterizer: yes, no
  -aa <string>            : enable font anti-aliasing: yes, no
  -aaVector <string>      : enable vector anti-aliasing: yes, no
  -opw <string>           : owner password (for encrypted files)
  -upw <string>           : user password (for encrypted files)
  -q                      : don't print any messages or errors
  -cfg <string>           : configuration file to use in place of .xpdfrc
  -v                      : print copyright and version info
  -h                      : print usage information
  -help                   : print usage information
  --help                  : print usage information
  -?                      : print usage information
```

Inferred after consideration:
* all pages to print
* DPI (default is 150)
* TIFF compression
* no alpha channel
* no passwords
* print messages and errors
* don't print usage information

**Comment by cpp-tutor** [comment]
I've made a version that prints more info by default, however I still feel that the user is expected to be familiar with the other xpdf tools.

Please find attached: [pdftotiff-with-infos.zip](https://github.com/cpp-tutor/xpdf-tiff-patches/files/9438153/pdftotiff-with-infos.zip)

**Comment by flywire** [comment]
Nice. I think that would be worthwhile for all the utilities.

Even better, I learnt `CCITT for -mono`.
