### ISSUE TITLE
No -tiff option for pdfimages

### ISSUE THREAD

**Issue by rubisco57** [cpp-tutor/xpdf-tiff-patches#3]
This is a great patch, however, how do I make available the libtiff tools as advised in the description ‹[...] pdfimages now also has -tiff option (when libtiff is available) [...]›?

**Comment by cpp-tutor** [comment]
The patch includes a change to the CMake build system which looks for libtiff. If target "pdftotiff" builds successfully then target "pdfimages" should also build and provide the -tiff option without further configuration.

Assuming that you have got this far, I'm uncertain about your reference to "the libtiff tools" which would need to be built outside of the xpdf source tree (when building libtiff). I only have limited knowledge of libtiff and not knowing which platform you are targeting means that I am uncertain about how to advise.

**Comment by cpp-tutor** [comment]
Just to clarify, the second patch for TIFF-aware "pdfimages" can be applied to the same or a different source tree. If same, choose "no" to both "undo" and "reapply patch" when prompted.
